[package]
name = "jmanuel1/sustainability-modeling-and-simulation"
version = "0.1.0"
authors = ["Jason Manuel <jama.indo@hotmail.com>"]
description = "The best package ever released"
homepage = "https://github.com/jmanuel1/sustainability-modeling-and-simulation"
repository = "https://github.com/jmanuel1/sustainability-modeling-and-simulation"
readme = "README.md"
license = "MIT"
keywords = ["sustainability", "environment"]
exclude = []

[dependencies]
# Idris 1.3.3-compatible fork
"legacy/probability" = { git = "https://github.com/lambdacasserole/probability", tag = "4fdba1dd9ae8dbfebcb135f6cf3ce996784101f5" }

[[targets.bin]]
# the name of the binary to create
name = "main"
# the path which contains all of the bin files (*cannot* be a parent directory)
# this is set to "src" by default
path = "src/"
# the path to the Main module of the binary
main = "Main"
